# Generated by Django 2.2.1 on 2020-02-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='codservicio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
