# Generated by Django 2.2.5 on 2020-02-22 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('codcliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.CharField(blank=True, max_length=100)),
                ('numcuenta', models.CharField(blank=True, max_length=50)),
                ('foto', models.ImageField(blank=True, upload_to='clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('codservicio', models.IntegerField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, upload_to='servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('codreserva', models.IntegerField(primary_key=True, serialize=False)),
                ('fechareserva', models.DateField()),
                ('clientes_codcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.Clientes')),
                ('servicios_codservicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.Servicios')),
            ],
        ),
    ]
